name: API CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.3.2"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: gleam deps download
        working-directory: api
      - run: gleam test
        working-directory: api
